<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909220049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria as tabelas assunto, autor, livro, livro_autor e livro_assunto';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE assunto (codas INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descricao VARCHAR(20) NOT NULL, PRIMARY KEY (codas))');
        $this->addSql('CREATE TABLE autor (codau INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(40) NOT NULL, PRIMARY KEY (codau))');
        $this->addSql('CREATE TABLE livro (codl INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(40) NOT NULL, editora VARCHAR(40) NOT NULL, edicao INT NOT NULL, ano_publicacao VARCHAR(4) NOT NULL, valor NUMERIC(10, 2) NOT NULL, PRIMARY KEY (codl))');
        $this->addSql('CREATE TABLE livro_autor (livro_codl INT NOT NULL, autor_codau INT NOT NULL, PRIMARY KEY (livro_codl, autor_codau))');
        $this->addSql('CREATE INDEX IDX_6749992A53550D7 ON livro_autor (livro_codl)');
        $this->addSql('CREATE INDEX IDX_67499926696BB47 ON livro_autor (autor_codau)');
        $this->addSql('CREATE TABLE livro_assunto (livro_codl INT NOT NULL, assunto_codas INT NOT NULL, PRIMARY KEY (livro_codl, assunto_codas))');
        $this->addSql('CREATE INDEX IDX_53C2C52AA53550D7 ON livro_assunto (livro_codl)');
        $this->addSql('CREATE INDEX IDX_53C2C52A831BDC55 ON livro_assunto (assunto_codas)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE livro_autor ADD CONSTRAINT FK_6749992A53550D7 FOREIGN KEY (livro_codl) REFERENCES livro (codl) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livro_autor ADD CONSTRAINT FK_67499926696BB47 FOREIGN KEY (autor_codau) REFERENCES autor (codau) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livro_assunto ADD CONSTRAINT FK_53C2C52AA53550D7 FOREIGN KEY (livro_codl) REFERENCES livro (codl) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livro_assunto ADD CONSTRAINT FK_53C2C52A831BDC55 FOREIGN KEY (assunto_codas) REFERENCES assunto (codas) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE livro_autor DROP CONSTRAINT FK_6749992A53550D7');
        $this->addSql('ALTER TABLE livro_autor DROP CONSTRAINT FK_67499926696BB47');
        $this->addSql('ALTER TABLE livro_assunto DROP CONSTRAINT FK_53C2C52AA53550D7');
        $this->addSql('ALTER TABLE livro_assunto DROP CONSTRAINT FK_53C2C52A831BDC55');
        $this->addSql('DROP TABLE assunto');
        $this->addSql('DROP TABLE autor');
        $this->addSql('DROP TABLE livro');
        $this->addSql('DROP TABLE livro_autor');
        $this->addSql('DROP TABLE livro_assunto');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
