<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260909220049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria as tabelas assunto, autor, livro, livro_autor e livro_assunto';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assunto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descricao VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE autor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(40) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE livro (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(40) NOT NULL, editora VARCHAR(40) NOT NULL, edicao INT NOT NULL, ano_publicacao VARCHAR(4) NOT NULL, valor NUMERIC(10, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE livro_autor (livro_id INT NOT NULL, autor_id INT NOT NULL, PRIMARY KEY (livro_id, autor_id))');
        $this->addSql('CREATE INDEX IDX_67499925864C5AF ON livro_autor (livro_id)');
        $this->addSql('CREATE INDEX IDX_674999214D45BBE ON livro_autor (autor_id)');
        $this->addSql('CREATE TABLE livro_assunto (livro_id INT NOT NULL, assunto_id INT NOT NULL, PRIMARY KEY (livro_id, assunto_id))');
        $this->addSql('CREATE INDEX IDX_53C2C52A5864C5AF ON livro_assunto (livro_id)');
        $this->addSql('CREATE INDEX IDX_53C2C52A4CE74285 ON livro_assunto (assunto_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE livro_autor ADD CONSTRAINT FK_67499925864C5AF FOREIGN KEY (livro_id) REFERENCES livro (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livro_autor ADD CONSTRAINT FK_674999214D45BBE FOREIGN KEY (autor_id) REFERENCES autor (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livro_assunto ADD CONSTRAINT FK_53C2C52A5864C5AF FOREIGN KEY (livro_id) REFERENCES livro (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livro_assunto ADD CONSTRAINT FK_53C2C52A4CE74285 FOREIGN KEY (assunto_id) REFERENCES assunto (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE livro_autor DROP CONSTRAINT FK_67499925864C5AF');
        $this->addSql('ALTER TABLE livro_autor DROP CONSTRAINT FK_674999214D45BBE');
        $this->addSql('ALTER TABLE livro_assunto DROP CONSTRAINT FK_53C2C52A5864C5AF');
        $this->addSql('ALTER TABLE livro_assunto DROP CONSTRAINT FK_53C2C52A4CE74285');
        $this->addSql('DROP TABLE assunto');
        $this->addSql('DROP TABLE autor');
        $this->addSql('DROP TABLE livro');
        $this->addSql('DROP TABLE livro_autor');
        $this->addSql('DROP TABLE livro_assunto');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
