name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: thiagoguilherme71
          password: ${{ secrets.THIAGOGUILHERME71 }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thiagoguilherme71/acervo-livros-symfony:latest
            thiagoguilherme71/acervo-livros-symfony:${{ github.sha }}